var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/why-client-care-must-come-first/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0c6ee05e._.js")
R.c("server/chunks/ssr/_a3b9117b._.js")
R.c("server/chunks/ssr/_4156c271._.js")
R.c("server/chunks/ssr/[root-of-the-server]__a30af444._.js")
R.c("server/chunks/ssr/[root-of-the-server]__97ee9bf5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_982e7503._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_bf968cdb._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_why-client-care-must-come-first_page_actions_6838aa82.js")
R.m(80347)
module.exports=R.m(80347).exports
